name: Build Executables

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            extension: .AppImage
          - os: macos-latest
            extension: .app
          - os: windows-latest
            extension: .exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller Pillow

    - name: Create Executable
      run: |
        pyinstaller --onefile --windowed --icon bullish.ico --add-data "light-off.png;." --add-data "light-on.png;." stock_split_calculator.py
      shell: bash

    - name: Upload Executable
      uses: actions/upload-artifact@v2
      with:
        name: stock_split_calculator-${{ matrix.os }}-${{ github.sha }}
        path: dist/stock_split_calculator${{ matrix.extension }}
